CREATE TABLE services (NAME VARCHAR(255) NOT NULL, PRICE FLOAT, PRIMARY KEY (NAME))
CREATE TABLE breeds (ID  SERIAL NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE status (NAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME))
