version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres-ifpb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ifpb
      POSTGRES_PASSWORD: ifpb
      POSTGRES_DB: pets
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ifpb
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ifpb@ifpb.edu.br
      PGADMIN_DEFAULT_PASSWORD: ifpb
    ports:
      - "80:80"
      - "443:443"


